version: "3.1"

services:
  db:
    container_name: dropstar-api-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - "${DB_PORT}"
    networks:
      default:
        ipv4_address: ${DB_HOST}
    volumes:
      - ${PWD}/dropstar-api-db/postgres:/var/lib/mysql
      - ${PWD}/dropstar-api-db/server.crt:/var/lib/postgresql/server.crt:ro
      - $(PWD)/dropstar-api-db/server.key:/var/lib/postgresql/server.key:ro



docker run -d \
    --name postgres \
    -e POSTGRES_HOST_AUTH_METHOD=trust \
    postgres:12-alpine \
    -c ssl=on \
    -c ssl_cert_file=/var/lib/postgresql/server.crt \
    -c ssl_key_file=/var/lib/postgresql/server.key

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK}
